### ISSUE TITLE
As a user, I want to be able to create a new drawing by clicking on the draw link

### ISSUE THREAD

**Issue by Kistinagrg** [genius-geminis/color-i-sing#2]
- [ ] create user model db [#10]
- [ ] create finshedImages model db [#11]
- [ ] create homepage route [#12]
- [ ] create draw route [#13]
- [ ] create homepage component [#15]
- [ ] create draw view component [#17]
