### ISSUE TITLE
As a user, I can sign in, log in, and logout

### ISSUE THREAD

**Issue by colleen-higgins-designs** [genius-geminis/color-i-sing#3]
- [ ] create local log in/ sign up page [#24]
- [ ] connect log in to oauth [#25]
- [ ] create logout button [#26]
