### ISSUE TITLE
As a user, I can use my mic to color in the canvas

### ISSUE THREAD

**Issue by colleen-higgins-designs** [genius-geminis/color-i-sing#5]
- [ ] create hash map for colors - frequencies [#19]
- [ ] create getFrequency function [#20]
- [ ] create getColor function  [#22]
- [ ] create getNextPixel function [#23]
- [ ] create draw view [#17]
